Peliculas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.urls import path 
from . import views 

app_name = 'app' 
urlpatterns = [
    path('inicio/', views.inicio, name='inicio'), 
    path('categorias/', views.categorias, name='categorias'), 
    path('categorias/<int:id>/', views.categoria, name='categoria'), 
    path('peliculas/', views.peliculas, name='peliculas'), 
]

app/models.py
from typing_extensions import Self
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre=models.CharField(max_length=100, null=False)
    descripcion=models.TextField(null=True)
    
    def __str__(self):
        return self.nombre

    class Meta:
        app_label='app'

class Pelicula(models.Model):
    titulo=models.CharField(max_length=500, null=False)
    year=models.IntegerField(null=True)
    # on_delete para que no se borre en cascada
    categoria=models.ForeignKey(Categoria, related_name='peliculas', null=False, on_delete=models.PROTECT)
    fecha_creacion=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo

    class Meta:
        app_label='app'

app/views.py
from http.client import HTTPResponse
from multiprocessing import context
from django.shortcuts import render
from django.http import HttpResponse
from app.models import Categoria

# Create your views here.

def peliculas(request):
    return HttpResponse ('Peliculas')

def inicio(request):
    return render (request,'app/inicio.html')

def categorias(request):

    lista_categorias=Categoria.objects.all()

    contexto={
        'titulo':'Blockbuster',
        'categorias':[
        {'id':1, 'nombre': 'terror'},
        {'id':2, 'nombre': 'romance'},
        {'id':3, 'nombre': 'aventuras'},
        {'id':4, 'nombre': 'Comedia'},

        ]
    }
    
    return render(request, 'app/base.html',contexto)

def categoria(request, id):
    return HttpResponse (f'Esta es una Categoria {id}')

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Votaciones USTA</title>
    <link rel="stylesheet" href="./CSS/ListaVotaciones.css">
    <link rel="stylesheet" href="CSS/header.css">
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}" />

    <!-- ICONOS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body> 
    <!-- header, contenedor -->
    <div class="contenedor">
        <div class="header">
            <button><i class="fa-solid fa-bars"></i></button>
            <img src="pictures/Logotipo_USTA_Colombia.gif" alt="logo" class="LogoUSTA"></a>
            <h1>VOTACIONES USTA</h1>
            <!--nav crea enlaces de navegaciòn -->
            <nav class="menu">
                <ul>
                    <li><a href="menuEstudiante.html">Inicio</a></li>
                    <li><a href="../decano/login.html">Salir</a></li>
                </ul>
            </nav>
        </div> 
        <div class="opciones">
            <nav class="menu2">
                <ul>
                    <h2>MENU</h2>
                    <li><a href="{% url 'app:categorias'%}">Lista de Votaciones</a></li>
                    <li><a href="listaResultados.html">Lista de Resultados</a></li>
                    <li><a href="HistoricoVotaciones.html">Historico de votaciones</a></li>
                </ul>
            </nav>
        </div>
        <div class="contenido">

            {% block contenido%}
            {% endblock %}         
                
        </div> 
    </div>
    
</body>
</html>

app/templates/app/categorias.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=[device-width], initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%if categoria%}
    <h1>{{titulo}}</h1>
    {%else%}
    <h1>No hay titulo</h1>
    {%endif%}
    
    {% extends 'app/base.html' %} {% block contenido %}

<h1>Categorias</h1>
<ul id="lista-categorias">
  {% for categoria in categorias %}
  <li>
    <a href="{% url 'app:categoria' categoria.id %}"></a>
  </li>
  {% endfor %}
</ul>

{% endblock %} {% block titulo %} Categorias {% endblock %}
</body>
</html>

app/templates/app/inicio.html
{% extends "app/base.html" %}

{% block contenido%}

<h1>Lista de Votaciones</h1>
             <p>En este listado encontrará todas las votaciones en las cuales podrá postularse o elegir su candidato favorito</p>
             <div class="tabla">
                <table>
                    <tr class="TitulosTabla">
                        <td>Nombre</td>
                        <td>Tipo</td>
                        <td>Fecha de inicio</td>
                        <td>Fecha de finalización</td>
                        <td>Ciclo</td>
                        <td>Votar</td>
                        <td>Postularse</td>
                    </tr>
                    <tr class="ContenidoTabla">
                       <td>Nombre 1</td>
                       <td>Facultad</td>
                       <td>10/10/10</td>
                       <td>10/10/10</td>
                       <td>2022-1</td>
                       <td>
                           <a href="votarcandidato.html">
                            <i class="fa-solid fa-check-to-slot"></i> 
                           </a>
                       </td>
                       <td>
                           <a href="Postulacion.html">
                            <i class="fa-solid fa-user-plus"></i>
                           </a>
                       </td>
                   </tr>

                   <tr class="ContenidoTabla">
                       <td>Nombre 2</td>
                       <td>Semestre</td>
                       <td>10/10/10</td>
                       <td>10/10/10</td>
                       <td>2022-1</td>
                       <td>
                        <a href="votarcandidato.html">
                         <i class="fa-solid fa-check-to-slot"></i> 
                        </a>
                    </td>
                    <td>
                        <a href="Postulacion.html">
                         <i class="fa-solid fa-user-plus"></i>
                        </a>
                    </td>
                   </tr>
                   <tr class="ContenidoTabla">
                       <td>Nombre 3</td>
                       <td>Semestre</td>
                       <td>10/10/10</td>
                       <td>10/10/10</td>
                       <td>2022-1</td>
                       <td>
                        <a href="votarcandidato.html">
                         <i class="fa-solid fa-check-to-slot"></i> 
                        </a>
                    </td>
                    <td>
                        <a href="Postulacion.html">
                         <i class="fa-solid fa-user-plus"></i>
                        </a>
                    </td>
                   </tr>
                   <tr class="ContenidoTabla">
                    <td>Nombre 4</td>
                    <td>Facultad</td>
                    <td>10/10/10</td>
                    <td>10/10/10</td>
                    <td>2022-1</td>
                    <td>
                        <a href="votarcandidato.html">
                         <i class="fa-solid fa-check-to-slot"></i> 
                        </a>
                    </td>
                    <td>
                        <a href="Postulacion.html">
                         <i class="fa-solid fa-user-plus"></i>
                        </a>
                    </td>
                </tr>
                </table> 
            </div>
{% endblock %} 